services:
  # -------------------------------------
  # Zabbix Server
  # -------------------------------------
  postgres:
    image: docker.io/postgres:13.8-alpine3.16
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=zabbix
    volumes:
      - postgres-map-build:/var/lib/postgresql/data
    networks:
      zabbix-network:
        ipv4_address: 172.16.80.10
  
  zabbix-server:
    image: docker.io/zabbix/zabbix-server-pgsql:alpine-6.0-latest
    container_name: zabbix-server
    restart: unless-stopped
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=password
    networks:
      zabbix-network:
        ipv4_address: 172.16.80.11
      router-network:
        ipv4_address: 172.16.80.138
  
  zabbix-web:
    image: docker.io/zabbix/zabbix-web-nginx-pgsql:alpine-6.0-latest
    container_name: zabbix-web
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=password
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Europe/Paris
    networks:
      zabbix-network:
        ipv4_address: 172.16.80.12
    
  # -------------------------------------
  # Routers
  # -------------------------------------
  router-1:
    build: ./build/router
    container_name: router-1
    restart: unless-stopped
    volumes:
      - ./examples/data/router-1.snmpwalk:/data/router-1.snmpwalk
    networks:
      router-network:
        ipv4_address: 172.16.80.161


  router-2:
    build: ./build/router
    container_name: router-2
    restart: unless-stopped
    volumes:
      - ./examples/data/router-2.snmpwalk:/data/router-2.snmpwalk
    networks:
      router-network:
        ipv4_address: 172.16.80.162

  router-3:
    build: ./build/router
    container_name: router-3
    restart: unless-stopped
    volumes:
      - ./examples/data/router-3.snmpwalk:/data/router-3.snmpwalk
    networks:
      router-network:
        ipv4_address: 172.16.80.163

volumes:
  postgres-map-build:

networks:
  zabbix-network:
    ipam:
      config:
        - subnet: 172.16.80.0/25
          ip_range: 172.16.80.1/25
          gateway: 172.16.80.126
  router-network:
    ipam:
      config:
        - subnet: 172.16.80.128/25
          ip_range: 172.16.80.129/25
          gateway: 172.16.80.254