services:
  # -------------------------------------
  # Zabbix Server
  # -------------------------------------
  postgres:
    image: docker.io/postgres:13.8-alpine3.16
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=zabbix
    volumes:
      - postgres-map-build:/var/lib/postgresql/data
  
  zabbix-server:
    image: docker.io/zabbix/zabbix-server-pgsql:alpine-6.0-latest
    container_name: zabbix-server
    restart: unless-stopped
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=password
  
  zabbix-web:
    image: docker.io/zabbix/zabbix-web-nginx-pgsql:alpine-6.0-latest
    container_name: zabbix-web
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=password
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Europe/Paris
    
  # -------------------------------------
  # Routers
  # -------------------------------------
  router-1:
    build: ./build/router
    container_name: router-1
    restart: unless-stopped
    volumes:
      - ./examples/data/router-1.snmpwalk:/data/router-1.snmpwalk

  router-2:
    build: ./build/router
    container_name: router-2
    restart: unless-stopped
    volumes:
      - ./examples/data/router-2.snmpwalk:/data/router-2.snmpwalk

  router-3:
    build: ./build/router
    container_name: router-3
    restart: unless-stopped
    volumes:
      - ./examples/data/router-3.snmpwalk:/data/router-3.snmpwalk

volumes:
  postgres-map-build:
  